services:
  # 1. Node.js Backend Service
  - type: web
    name: resume-backend-node
    env: node
    rootDir: backend-node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: AI_SERVICE_URL
        fromService:
          type: web
          name: resume-ai-service
          property: hostport

  # 2. Python AI Service
  - type: web
    name: resume-ai-service
    env: python
    rootDir: ai-service-python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
